"""Centralised error code constants — merged from Deal + RFQ agents."""

# RFQ error codes
ERR_INVALID_PERSONA = "RTQ-001"
ERR_INVALID_SIMULATION = "RTQ-002"
ERR_GUARDRAIL_VIOLATION = "RTQ-003"
ERR_METADATA_LOAD = "RTQ-010"
ERR_DATA_RETRIEVAL = "RTQ-020"
ERR_TOOL_CALL = "RTQ-021"
ERR_LLM_CALL = "RTQ-030"
ERR_AGENT_LOOP_EXCEEDED = "RTQ-031"
ERR_SCHEMA_VALIDATION = "RTQ-040"
ERR_CONVERSATION_PERSIST = "RTQ-050"

# Deal agent error codes
ERR_CONVERSATION_NOT_FOUND = "DEAL-001"
ERR_AGENT_PROCESSING_FAILED = "DEAL-002"
ERR_TOOL_EXECUTION_FAILED = "DEAL-003"

# Unified error codes
ERR_INVALID_AGENT_TYPE = "UNI-001"
