"""Centralized error code constants."""

INVALID_PARAMS = "INVALID_PARAMS"
INTERNAL_ERROR = "INTERNAL_ERROR"
TRADER_NOT_FOUND = "TRADER_NOT_FOUND"
SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
DATABRICKS_TRIGGER_FAILED = "DATABRICKS_TRIGGER_FAILED"
DATABASE_ERROR = "DATABASE_ERROR"

"""Centralized error code constants for the Deal Intelligence Agent."""

# Resource not found errors
CHAT_NOT_FOUND: str = "CHAT_NOT_FOUND"
DOCUMENT_NOT_FOUND: str = "DOCUMENT_NOT_FOUND"

# Validation errors
INVALID_ANALYST_TYPE: str = "INVALID_ANALYST_TYPE"
INVALID_SCENARIO_TYPE: str = "INVALID_SCENARIO_TYPE"
INVALID_FILE_TYPE: str = "INVALID_FILE_TYPE"
INVALID_UUID_FORMAT: str = "INVALID_UUID_FORMAT"
MISSING_REQUIRED_FIELD: str = "MISSING_REQUIRED_FIELD"
VALIDATION_ERROR: str = "VALIDATION_ERROR"

